:schedule:
  sms_hub_interval_sender_notification_checker:
    # cron: '0 */5 * * * *' # Runs once every 5 minutes
    every: '20m'
    # every: '30s'
    queue: standard_delivery
    class: SmsHubIntervalSenderNotificationJob
